# Support the author by using the funding links below
# Developed and maintained by ataglianetti with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/ataglianetti
# Buy Me a Coffee: https://buymeacoffee.com/ataglianetti

buy_me_a_coffee: ataglianetti

# Your support means a lot to me to continue the development of open source projects like this.
# Sponsoring this project means a lot to me. Your support helps me to continue building great
# open-source projects just like this.